main: dev.orangeben.blinklink.BLPlugin
name: BlinkLink
api-version: 1.20
version: 1.2
depend: [NBTAPI]
commands:
  blinklink:
    description: Reloads the blinklink config
    usage: /blinklink
    permission: