main: dev.orangeben.blinklink.BlinkLink
name: BlinkLink
api-version: 1.20
version: 1.1
depend: [NBTAPI]
commands:
  blinklink:
    description: Reloads the blinklink config
    usage: /blinklink
    permission: